//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Nullable<int> Id { get; set; }
        public string UserName { get; set; }
        public int CentreId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Centre Centre { get; set; }
    }
}
